logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/shopping?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'TRUE'
  mail:
    host: smtp.gmail.com
    port: 587
    username: springappmail77@gmail.com
    password: ueaq kcah vdfj ipmd
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          write timeout: 10000
          connection-timeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080